name: Test Artifact
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Mon application" > my_app.txt
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: |
          ls
          cat my_app.txt
       
            
