name: Secret
on: push
jobs:
  display-values:
    runs-on: ubuntu-latest
    outputs:
      MON_RETOUR: ${{ steps.step-return.outputs.result }}
    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      - name: GitHub Script
        id: step-return
        uses: actions/github-script@v7.0.1
        with:
          # The script to run
          script: |
              return "Mon retour"
  display-return:
    runs-on: ubuntu-latest
    needs: [display-values]
    steps:
      - run: echo "${{ needs.display_values.outputs.MON_RETOUR }}"
       
            
