name: Secret
on: push
jobs:
  display-values:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      - name: GitHub Script
        uses: actions/github-script@v7.0.1
        with:
          # The script to run
          script: |
              return "Mon retour"
            
